### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [DeliasZen/kinozal-template#1]
1)

Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/143875125-bb71269d-191e-4caf-9993-bdc3f705373c.png)

2)

Отступы не соответствуют поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/143875413-352de5a0-d2af-4c5b-84bf-17785c8a079f.png)

**Comment by DeliasZen** [comment]
SkillUp FrontEnd. Шутиков Илья, вт/чт 20:15

Ошибки по замечаниям исправлены.
Направляю исправленную контрольную работу "kinozal-template".

Ссылка на Git: https://github.com/DeliasZen/kinozal-template.git

Ссылка на Git-Pages: https://deliaszen.github.io/kinozal-template/

пн, 29 нояб. 2021 г. в 16:22, Andrey ***@***.***>:

**Comment by Alecto** [comment]
Теперь правильно, больше ошибок и замечаний нет.
Работа принята.

пн, 29 лист. 2021 о 16:09 Ilya Shutikov ***@***.***> пише:
